### ISSUE TITLE
Miss Train Process

### ISSUE THREAD

**Issue by alisea47** [chenxran/Orion#1]
Hello, the open-source code only has the code for the evaluation part.
As for the training process, only puts out 2 trained models. How does the training process work? 
Could you please give me an example code?
Thank you very much!

**Comment by chenxran** [comment]
The models provided in this repo are trained over two simple MLM tasks, respectively. Our implementation is based on [run_mlm.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py) in Huggingface transformers, and the training corpus is Wikipedia provided in Huggingface datasets. For data preprocessing, we first used spacy to annotate all the entities within the corpus. Then, to train for P(ins|r_p), we mask **all the entities** to train the model; to train for P(r_h|ins), we mask **all the text except entities** to train the model.
